<?php

namespace RuralisBundle\Repository;

/**
 * AbonneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbonneRepository extends \Doctrine\ORM\EntityRepository
{
}
