<?php

namespace RuralisBundle\Repository;

/**
 * AbonnementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbonnementRepository extends \Doctrine\ORM\EntityRepository
{
    public function ContactAboNewsletter()
    {
        $qb = $this->createQueryBuilder('a');
        $qb->select('c.email')
            ->join('a.contact', 'c')
            ->where('a.newsletter = true');

        return $qb->getQuery()->getResult();
    }
}