<?php

namespace RuralisBundle\Repository;

/**
 * TypeAbonnementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeAbonnementRepository extends \Doctrine\ORM\EntityRepository
{
}
