<?php

namespace RuralisBundle\Repository;

/**
 * TypeAboRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeAboRepository extends \Doctrine\ORM\EntityRepository
{
}
