<?php

namespace RuralisBundle\Repository;

/**
 * TypeAffichageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeAffichageRepository extends \Doctrine\ORM\EntityRepository
{
}
